// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRXixej7ZYNvQpo6qU-BsAbNn3cpKmQAk',
    appId: '1:1063269685609:web:41f9c92d076391a29ec5f8',
    messagingSenderId: '1063269685609',
    projectId: 'juan-heart-project',
    authDomain: 'juan-heart-project.firebaseapp.com',
    storageBucket: 'juan-heart-project.firebasestorage.app',
    measurementId: 'G-114BG2QMN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9KqhdT7It9_bFCOj0PtIMnVpECXbAuw',
    appId: '1:1063269685609:android:55b3b454738ec6069ec5f8',
    messagingSenderId: '1063269685609',
    projectId: 'juan-heart-project',
    storageBucket: 'juan-heart-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfNvrGEMc4TP18vp0FRIqvcIrRFPji6QU',
    appId: '1:1063269685609:ios:4531431e547a2cbc9ec5f8',
    messagingSenderId: '1063269685609',
    projectId: 'juan-heart-project',
    storageBucket: 'juan-heart-project.firebasestorage.app',
    iosBundleId: 'com.example.healthifys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfNvrGEMc4TP18vp0FRIqvcIrRFPji6QU',
    appId: '1:1063269685609:ios:39f3497598f3ade29ec5f8',
    messagingSenderId: '1063269685609',
    projectId: 'juan-heart-project',
    storageBucket: 'juan-heart-project.firebasestorage.app',
    iosBundleId: 'com.example.healthify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRXixej7ZYNvQpo6qU-BsAbNn3cpKmQAk',
    appId: '1:1063269685609:web:c4dd66b28fe9a65e9ec5f8',
    messagingSenderId: '1063269685609',
    projectId: 'juan-heart-project',
    authDomain: 'juan-heart-project.firebaseapp.com',
    storageBucket: 'juan-heart-project.firebasestorage.app',
    measurementId: 'G-E1SR8RGE75',
  );
}
